name: Main Branch Guard

on:
  push:
    branches:
      - main

jobs:
  validate-and-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...

      - name: Download dependencies
        run: go mod download

      - name: Lint with Go Official Tools
        run: |
          echo "Running go vet to check for suspicious constructs..."
          go vet ./...
          
          echo "Checking for unformatted files..."
          unformatted=$(gofmt -l .)
          if [ -n "$unformatted" ]; then
            echo "Error: The following files are not formatted. Please run 'go fmt ./...' locally and commit the changes."
            echo "$unformatted"
            exit 1
          fi
          echo "All files are correctly formatted."

      - name: Verify Generated Files Consistency
        run: |
          echo "Running generators to verify consistency..."
          
          # 调用生成器工具生成临时文件
          go run github.com/meloshub/meloshub-tools/cmd/autoimport@latest --output ./all/all.go.tmp --pkg all
          go run github.com/meloshub/meloshub-tools/cmd/metagen@latest --output adapters.yaml.tmp

          # 比较临时文件和仓库中的文件
          echo "Comparing all/all.go with temporary file..."
          diff ./all/all.go ./all/all.go.tmp
          
          echo "Comparing adapters.yaml with temporary file..."
          diff adapters.yaml adapters.yaml.tmp
          
          echo "Generated files are consistent. Check passed."

      - name: Run Go Vulnerability Check
        run: go install golang.org/x/vuln/cmd/govulncheck@latest && govulncheck ./...